name: CI

on: 
  push:
    branches:
      - master

jobs:
  deploy-on-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:	
          node-version: 10.x
  
      - name: Yarn install BE
        run: yarn
 
      - name: Yarn Install and Build FE
        run: |
          cd client
          yarn
          yarn run build
      
      - name: Lint
        run: |
          cd client
          yarn lint .  

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/serene-shelf-23946.git origin/master:master
